# -*- coding: utf-8 -*-
"""screen_beta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RofcS56wRaRz1Sq0lm10knlK9rmVXRHR
"""

# Save this code as app.py and run with `streamlit run app.py`
import streamlit as st

st.set_page_config(page_title="ChatGPT Black", layout="centered")

st.markdown(
    """
    <style>
    .stApp {
        background-color: black;
        color: white;
    }
    .user-msg {
        color: lightgreen;
    }
    .bot-msg {
        color: cyan;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.title("🖤 ChatGPT Black Theme")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    if msg["role"] == "user":
        st.markdown(f'<div class="user-msg">🧑 {msg["content"]}</div>', unsafe_allow_html=True)
    else:
        st.markdown(f'<div class="bot-msg">🤖 {msg["content"]}</div>', unsafe_allow_html=True)

user_input = st.text_input("You:", key="input")
if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})
    response = "This is a placeholder response."
    st.session_state.messages.append({"role": "bot", "content": response})
    st.experimental_rerun()