# -*- coding: utf-8 -*-
"""screen_beta_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RofcS56wRaRz1Sq0lm10knlK9rmVXRHR
"""

import streamlit as st

# Configura a página
st.set_page_config(page_title="ChatGPT Light+", layout="centered")

# Estilo customizado: claro, porém com um fundo levemente acinzentado
st.markdown(
    """
    <style>
    .stApp {
        background-color: #f2f3f5;
        color: #1f1f1f;
        padding-bottom: 100px;
    }

    .user-msg, .bot-msg {
        font-size: 16px;
        padding: 12px 16px;
        margin: 10px;
        border-radius: 20px;
        max-width: 80%;
        word-wrap: break-word;
        box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    }

    .user-msg {
        background-color: #d2f4dc;
        color: #1a3d2f;
        margin-left: auto;
        text-align: right;
    }

    .bot-msg {
        background-color: #e6e9ef;
        color: #1f1f1f;
        margin-right: auto;
    }

    .bottom-input {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        width: 100%;
        background-color: #f2f3f5;
        padding: 20px;
        box-shadow: 0 -2px 10px rgba(0,0,0,0.1);
        z-index: 10;
    }

    input[type="text"] {
        background-color: #ffffff;
        color: #000000;
        padding: 12px;
        border-radius: 10px;
        border: 1px solid #ccc;
        width: 100%;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Título discreto
st.title("💬 Chat Light+")

# Inicializa o estado da sessão
if "messages" not in st.session_state:
    st.session_state.messages = []

# Exibe o histórico
for msg in st.session_state.messages:
    role_class = "user-msg" if msg["role"] == "user" else "bot-msg"
    emoji = "🧑‍💻" if msg["role"] == "user" else "🤖"
    st.markdown(f'<div class="{role_class}">{emoji} {msg["content"]}</div>', unsafe_allow_html=True)

# Campo de entrada fixo
st.markdown('<div class="bottom-input">', unsafe_allow_html=True)
user_input = st.text_input("You:", key="input", label_visibility="collapsed", placeholder="Type your message...")
st.markdown('</div>', unsafe_allow_html=True)

# Lógica simples
if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})
    response = "🤖 I'm responding to you!"
    st.session_state.messages.append({"role": "bot", "content": response})
    st.experimental_rerun()